services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Internetgalerie\IgMfaFrontend\:
    resource: "../Classes/*"

  Internetgalerie\IgMfaFrontend\EventListener\MfaModifyLoginFormViewEventListener:
    tags:
      - name: event.listener
        identifier: 'ig-mfa-frontend/MfaModifyLoginFormViewEventListener'

  Internetgalerie\IgMfaFrontend\EventListener\LoginMfaRequiredEventListener:
    tags:
      - name: event.listener
        identifier: 'ig-mfa-frontend/LoginMfaRequiredEventListener'